name: Run Postman Tests

on:
  push:
    branches:
      - main  # Runs on push to the main branch (or any specific branch you want)

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js (needed for Newman)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Or any Node.js version you need

      # Step 3: Install dependencies (Newman)
      - name: Install dependencies
        run: |
          npm install -g newman  # Install Newman globally
         

      # Step 3.1: Install reporter
      - name: Install Reporter
        run: |
           npm install -g newman-reporter-htmlextra 
          

      # Step 4: Run Postman tests with Newman
      - name: Run Postman Collection with Newman
        run: |
          newman run NewmanAPI/API_Chaning.postman_collection.json -r htmlextra  # Adjust path if needed

      # Step 5: Upload test results as artifact
      - name: Upload Newman Results
        uses: actions/upload-artifact@v4  # Use v4 of the artifact upload action
        with:
          name: report
          path: newman # Adjust path to where Newman results are saved
