name: Run Postman Tests

on:
  push:
    branches:
      - main  # Trigger on push to the main branch (or your default branch)
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js (this is needed for Newman)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Choose the Node.js version you need

      # Step 3: Install Newman globally
      - name: Install dependencies
        run: |
          npm install -g newman  # Install Newman globally

      # Step 4: Run Postman tests
      - name: Run Postman Collection with Newman
        run: |
          newman run NewmanAPI/API_Chaning.postman_collection.json  # Run your Postman collection

      # Optional: Step 5: Upload test results as an artifact for later review
      - name: Upload Newman Results
        uses: actions/upload-artifact@v2
        with:
          name: newman-results
          path: newman-results.json  # Adjust if you want to store detailed results for later
